
/* !! Generated using Vulkan XML spec version 132 !! */

/**
 * This file was auto-generated by the Vulkan Enum Converter
 * that is located at https://github.com/stablecoder/vk-enum-converter
 * or https://git.stabletec.com/utilities/vk-enum-converter
 *
 * Check for an updated version anytime, or state concerns/bugs.
 */

#include <algorithm>
#include <cctype>
#include <cstring>
#include <locale>
#include <memory>
#include <string>
#include <string_view>
#include <tuple>

namespace {

constexpr const char *vendorTags[] = {
    "IMG",    "AMD",  "AMDX",   "ARM",     "FSL",     "BRCM",     "NXP",       "NV",
    "NVX",    "VIV",  "VSI",    "KDAB",    "ANDROID", "CHROMIUM", "FUCHSIA",   "GGP",
    "GOOGLE", "QCOM", "LUNARG", "SAMSUNG", "SEC",     "TIZEN",    "RENDERDOC", "NN",
    "MVK",    "KHR",  "KHX",    "EXT",     "MESA",    "INTEL",
};
constexpr const std::size_t vendorTagCount = 30;

struct EnumDeclaration {
    const char *name;
    std::size_t count;
};
EnumDeclaration enumTypes[] = {
    {"VkImageLayout", 9},
    {"VkAttachmentLoadOp", 3},
    {"VkAttachmentStoreOp", 2},
    {"VkImageType", 3},
    {"VkImageTiling", 2},
    {"VkImageViewType", 7},
    {"VkCommandBufferLevel", 2},
    {"VkComponentSwizzle", 7},
    {"VkDescriptorType", 11},
    {"VkQueryType", 3},
    {"VkBorderColor", 6},
    {"VkPipelineBindPoint", 2},
    {"VkPipelineCacheHeaderVersion", 1},
    {"VkPrimitiveTopology", 11},
    {"VkSharingMode", 2},
    {"VkIndexType", 2},
    {"VkFilter", 2},
    {"VkSamplerMipmapMode", 2},
    {"VkSamplerAddressMode", 4},
    {"VkCompareOp", 8},
    {"VkPolygonMode", 3},
    {"VkCullModeFlagBits", 4},
    {"VkFrontFace", 2},
    {"VkBlendFactor", 19},
    {"VkBlendOp", 5},
    {"VkStencilOp", 8},
    {"VkLogicOp", 16},
    {"VkInternalAllocationType", 1},
    {"VkSystemAllocationScope", 5},
    {"VkPhysicalDeviceType", 5},
    {"VkVertexInputRate", 2},
    {"VkFormat", 185},
    {"VkStructureType", 49},
    {"VkSubpassContents", 2},
    {"VkDynamicState", 9},
    {"VkDescriptorUpdateTemplateType", 1},
    {"VkObjectType", 26},
    {"VkQueueFlagBits", 4},
    {"VkRenderPassCreateFlagBits", 0},
    {"VkDeviceQueueCreateFlagBits", 0},
    {"VkMemoryPropertyFlagBits", 5},
    {"VkMemoryHeapFlagBits", 1},
    {"VkAccessFlagBits", 17},
    {"VkBufferUsageFlagBits", 9},
    {"VkBufferCreateFlagBits", 3},
    {"VkShaderStageFlagBits", 8},
    {"VkImageUsageFlagBits", 8},
    {"VkImageCreateFlagBits", 5},
    {"VkImageViewCreateFlagBits", 0},
    {"VkSamplerCreateFlagBits", 0},
    {"VkPipelineCreateFlagBits", 3},
    {"VkPipelineShaderStageCreateFlagBits", 0},
    {"VkColorComponentFlagBits", 4},
    {"VkFenceCreateFlagBits", 1},
    {"VkSemaphoreCreateFlagBits", 0},
    {"VkFormatFeatureFlagBits", 13},
    {"VkQueryControlFlagBits", 1},
    {"VkQueryResultFlagBits", 4},
    {"VkCommandBufferUsageFlagBits", 3},
    {"VkQueryPipelineStatisticFlagBits", 11},
    {"VkImageAspectFlagBits", 4},
    {"VkSparseImageFormatFlagBits", 3},
    {"VkSparseMemoryBindFlagBits", 1},
    {"VkPipelineStageFlagBits", 17},
    {"VkCommandPoolCreateFlagBits", 2},
    {"VkCommandPoolResetFlagBits", 1},
    {"VkCommandBufferResetFlagBits", 1},
    {"VkSampleCountFlagBits", 7},
    {"VkAttachmentDescriptionFlagBits", 1},
    {"VkStencilFaceFlagBits", 4},
    {"VkDescriptorPoolCreateFlagBits", 1},
    {"VkDependencyFlagBits", 1},
    {"VkSemaphoreType", 2},
    {"VkSemaphoreWaitFlagBits", 1},
    {"VkPresentModeKHR", 4},
    {"VkColorSpaceKHR", 2},
    {"VkDisplayPlaneAlphaFlagBitsKHR", 4},
    {"VkCompositeAlphaFlagBitsKHR", 4},
    {"VkSurfaceTransformFlagBitsKHR", 9},
    {"VkSwapchainImageUsageFlagBitsANDROID", 1},
    {"VkTimeDomainEXT", 4},
    {"VkDebugReportFlagBitsEXT", 5},
    {"VkDebugReportObjectTypeEXT", 36},
    {"VkRasterizationOrderAMD", 2},
    {"VkExternalMemoryHandleTypeFlagBitsNV", 4},
    {"VkExternalMemoryFeatureFlagBitsNV", 3},
    {"VkValidationCheckEXT", 2},
    {"VkValidationFeatureEnableEXT", 3},
    {"VkValidationFeatureDisableEXT", 7},
    {"VkSubgroupFeatureFlagBits", 8},
    {"VkIndirectCommandsLayoutUsageFlagBitsNVX", 4},
    {"VkObjectEntryUsageFlagBitsNVX", 2},
    {"VkIndirectCommandsTokenTypeNVX", 8},
    {"VkObjectEntryTypeNVX", 5},
    {"VkDescriptorSetLayoutCreateFlagBits", 0},
    {"VkExternalMemoryHandleTypeFlagBits", 7},
    {"VkExternalMemoryFeatureFlagBits", 3},
    {"VkExternalSemaphoreHandleTypeFlagBits", 5},
    {"VkExternalSemaphoreFeatureFlagBits", 2},
    {"VkSemaphoreImportFlagBits", 1},
    {"VkExternalFenceHandleTypeFlagBits", 4},
    {"VkExternalFenceFeatureFlagBits", 2},
    {"VkFenceImportFlagBits", 1},
    {"VkSurfaceCounterFlagBitsEXT", 1},
    {"VkDisplayPowerStateEXT", 3},
    {"VkDeviceEventTypeEXT", 1},
    {"VkDisplayEventTypeEXT", 1},
    {"VkPeerMemoryFeatureFlagBits", 4},
    {"VkMemoryAllocateFlagBits", 1},
    {"VkDeviceGroupPresentModeFlagBitsKHR", 4},
    {"VkSwapchainCreateFlagBitsKHR", 0},
    {"VkViewportCoordinateSwizzleNV", 8},
    {"VkDiscardRectangleModeEXT", 2},
    {"VkSubpassDescriptionFlagBits", 0},
    {"VkPointClippingBehavior", 2},
    {"VkSamplerReductionMode", 3},
    {"VkTessellationDomainOrigin", 2},
    {"VkSamplerYcbcrModelConversion", 5},
    {"VkSamplerYcbcrRange", 2},
    {"VkChromaLocation", 2},
    {"VkBlendOverlapEXT", 3},
    {"VkCoverageModulationModeNV", 4},
    {"VkCoverageReductionModeNV", 2},
    {"VkValidationCacheHeaderVersionEXT", 1},
    {"VkShaderInfoTypeAMD", 3},
    {"VkQueueGlobalPriorityEXT", 4},
    {"VkDebugUtilsMessageSeverityFlagBitsEXT", 4},
    {"VkDebugUtilsMessageTypeFlagBitsEXT", 3},
    {"VkConservativeRasterizationModeEXT", 3},
    {"VkDescriptorBindingFlagBits", 4},
    {"VkVendorId", 4},
    {"VkDriverId", 12},
    {"VkConditionalRenderingFlagBitsEXT", 1},
    {"VkResolveModeFlagBits", 5},
    {"VkShadingRatePaletteEntryNV", 12},
    {"VkCoarseSampleOrderTypeNV", 4},
    {"VkGeometryInstanceFlagBitsNV", 4},
    {"VkGeometryFlagBitsNV", 2},
    {"VkBuildAccelerationStructureFlagBitsNV", 5},
    {"VkCopyAccelerationStructureModeNV", 2},
    {"VkAccelerationStructureTypeNV", 2},
    {"VkGeometryTypeNV", 2},
    {"VkAccelerationStructureMemoryRequirementsTypeNV", 3},
    {"VkRayTracingShaderGroupTypeNV", 3},
    {"VkMemoryOverallocationBehaviorAMD", 3},
    {"VkFramebufferCreateFlagBits", 0},
    {"VkScopeNV", 4},
    {"VkComponentTypeNV", 11},
    {"VkPipelineCreationFeedbackFlagBitsEXT", 3},
    {"VkFullScreenExclusiveEXT", 4},
    {"VkPerformanceCounterScopeKHR", 6},
    {"VkPerformanceCounterUnitKHR", 11},
    {"VkPerformanceCounterStorageKHR", 6},
    {"VkPerformanceCounterDescriptionFlagBitsKHR", 2},
    {"VkAcquireProfilingLockFlagBitsKHR", 0},
    {"VkShaderCorePropertiesFlagBitsAMD", 0},
    {"VkPerformanceConfigurationTypeINTEL", 1},
    {"VkQueryPoolSamplingModeINTEL", 1},
    {"VkPerformanceOverrideTypeINTEL", 2},
    {"VkPerformanceParameterTypeINTEL", 2},
    {"VkPerformanceValueTypeINTEL", 5},
    {"VkShaderFloatControlsIndependence", 3},
    {"VkPipelineExecutableStatisticFormatKHR", 4},
    {"VkLineRasterizationModeEXT", 4},
    {"VkShaderModuleCreateFlagBits", 0},
    {"VkPipelineCompilerControlFlagBitsAMD", 0},
    {"VkToolPurposeFlagBitsEXT", 5},
};
constexpr const std::size_t enumTypesCount = 167;

struct EnumValueSet {
    const char *name;
    uint32_t value;
};
constexpr const EnumValueSet VkImageLayoutSets[] = {
    {"UNDEFINED", 0},
    {"GENERAL", 1},
    {"COLOR_ATTACHMENT_OPTIMAL", 2},
    {"DEPTH_STENCIL_ATTACHMENT_OPTIMAL", 3},
    {"DEPTH_STENCIL_READ_ONLY_OPTIMAL", 4},
    {"SHADER_READ_ONLY_OPTIMAL", 5},
    {"TRANSFER_SRC_OPTIMAL", 6},
    {"TRANSFER_DST_OPTIMAL", 7},
    {"PREINITIALIZED", 8},
};
constexpr const EnumValueSet VkAttachmentLoadOpSets[] = {
    {"LOAD", 0},
    {"CLEAR", 1},
    {"DONT_CARE", 2},
};
constexpr const EnumValueSet VkAttachmentStoreOpSets[] = {
    {"STORE", 0},
    {"DONT_CARE", 1},
};
constexpr const EnumValueSet VkImageTypeSets[] = {
    {"1D", 0},
    {"2D", 1},
    {"3D", 2},
};
constexpr const EnumValueSet VkImageTilingSets[] = {
    {"OPTIMAL", 0},
    {"LINEAR", 1},
};
constexpr const EnumValueSet VkImageViewTypeSets[] = {
    {"1D", 0},       {"2D", 1},       {"3D", 2},         {"CUBE", 3},
    {"1D_ARRAY", 4}, {"2D_ARRAY", 5}, {"CUBE_ARRAY", 6},
};
constexpr const EnumValueSet VkCommandBufferLevelSets[] = {
    {"PRIMARY", 0},
    {"SECONDARY", 1},
};
constexpr const EnumValueSet VkComponentSwizzleSets[] = {
    {"IDENTITY", 0}, {"ZERO", 1}, {"ONE", 2}, {"R", 3}, {"G", 4}, {"B", 5}, {"A", 6},
};
constexpr const EnumValueSet VkDescriptorTypeSets[] = {
    {"SAMPLER", 0},
    {"COMBINED_IMAGE_SAMPLER", 1},
    {"SAMPLED_IMAGE", 2},
    {"STORAGE_IMAGE", 3},
    {"UNIFORM_TEXEL_BUFFER", 4},
    {"STORAGE_TEXEL_BUFFER", 5},
    {"UNIFORM_BUFFER", 6},
    {"STORAGE_BUFFER", 7},
    {"UNIFORM_BUFFER_DYNAMIC", 8},
    {"STORAGE_BUFFER_DYNAMIC", 9},
    {"INPUT_ATTACHMENT", 10},
};
constexpr const EnumValueSet VkQueryTypeSets[] = {
    {"OCCLUSION", 0},
    {"PIPELINE_STATISTICS", 1},
    {"TIMESTAMP", 2},
};
constexpr const EnumValueSet VkBorderColorSets[] = {
    {"FLOAT_TRANSPARENT_BLACK", 0}, {"INT_TRANSPARENT_BLACK", 1}, {"FLOAT_OPAQUE_BLACK", 2},
    {"INT_OPAQUE_BLACK", 3},        {"FLOAT_OPAQUE_WHITE", 4},    {"INT_OPAQUE_WHITE", 5},
};
constexpr const EnumValueSet VkPipelineBindPointSets[] = {
    {"GRAPHICS", 0},
    {"COMPUTE", 1},
};
constexpr const EnumValueSet VkPipelineCacheHeaderVersionSets[] = {
    {"ONE", 1},
};
constexpr const EnumValueSet VkPrimitiveTopologySets[] = {
    {"POINT_LIST", 0},
    {"LINE_LIST", 1},
    {"LINE_STRIP", 2},
    {"TRIANGLE_LIST", 3},
    {"TRIANGLE_STRIP", 4},
    {"TRIANGLE_FAN", 5},
    {"LINE_LIST_WITH_ADJACENCY", 6},
    {"LINE_STRIP_WITH_ADJACENCY", 7},
    {"TRIANGLE_LIST_WITH_ADJACENCY", 8},
    {"TRIANGLE_STRIP_WITH_ADJACENCY", 9},
    {"PATCH_LIST", 10},
};
constexpr const EnumValueSet VkSharingModeSets[] = {
    {"EXCLUSIVE", 0},
    {"CONCURRENT", 1},
};
constexpr const EnumValueSet VkIndexTypeSets[] = {
    {"UINT16", 0},
    {"UINT32", 1},
};
constexpr const EnumValueSet VkFilterSets[] = {
    {"NEAREST", 0},
    {"LINEAR", 1},
};
constexpr const EnumValueSet VkSamplerMipmapModeSets[] = {
    {"NEAREST", 0},
    {"LINEAR", 1},
};
constexpr const EnumValueSet VkSamplerAddressModeSets[] = {
    {"REPEAT", 0},
    {"MIRRORED_REPEAT", 1},
    {"CLAMP_TO_EDGE", 2},
    {"CLAMP_TO_BORDER", 3},
};
constexpr const EnumValueSet VkCompareOpSets[] = {
    {"NEVER", 0},
    {"LESS", 1},
    {"EQUAL", 2},
    {"LESS_OR_EQUAL", 3},
    {"GREATER", 4},
    {"NOT_EQUAL", 5},
    {"GREATER_OR_EQUAL", 6},
    {"ALWAYS", 7},
};
constexpr const EnumValueSet VkPolygonModeSets[] = {
    {"FILL", 0},
    {"LINE", 1},
    {"POINT", 2},
};
constexpr const EnumValueSet VkCullModeFlagBitsSets[] = {
    {"NONE", 0},
    {"FRONT_BIT", 0x00000001},
    {"BACK_BIT", 0x00000002},
    {"FRONT_AND_BACK", 0x00000003},
};
constexpr const EnumValueSet VkFrontFaceSets[] = {
    {"COUNTER_CLOCKWISE", 0},
    {"CLOCKWISE", 1},
};
constexpr const EnumValueSet VkBlendFactorSets[] = {
    {"ZERO", 0},
    {"ONE", 1},
    {"SRC_COLOR", 2},
    {"ONE_MINUS_SRC_COLOR", 3},
    {"DST_COLOR", 4},
    {"ONE_MINUS_DST_COLOR", 5},
    {"SRC_ALPHA", 6},
    {"ONE_MINUS_SRC_ALPHA", 7},
    {"DST_ALPHA", 8},
    {"ONE_MINUS_DST_ALPHA", 9},
    {"CONSTANT_COLOR", 10},
    {"ONE_MINUS_CONSTANT_COLOR", 11},
    {"CONSTANT_ALPHA", 12},
    {"ONE_MINUS_CONSTANT_ALPHA", 13},
    {"SRC_ALPHA_SATURATE", 14},
    {"SRC1_COLOR", 15},
    {"ONE_MINUS_SRC1_COLOR", 16},
    {"SRC1_ALPHA", 17},
    {"ONE_MINUS_SRC1_ALPHA", 18},
};
constexpr const EnumValueSet VkBlendOpSets[] = {
    {"ADD", 0}, {"SUBTRACT", 1}, {"REVERSE_SUBTRACT", 2}, {"MIN", 3}, {"MAX", 4},
};
constexpr const EnumValueSet VkStencilOpSets[] = {
    {"KEEP", 0},
    {"ZERO", 1},
    {"REPLACE", 2},
    {"INCREMENT_AND_CLAMP", 3},
    {"DECREMENT_AND_CLAMP", 4},
    {"INVERT", 5},
    {"INCREMENT_AND_WRAP", 6},
    {"DECREMENT_AND_WRAP", 7},
};
constexpr const EnumValueSet VkLogicOpSets[] = {
    {"CLEAR", 0},
    {"AND", 1},
    {"AND_REVERSE", 2},
    {"COPY", 3},
    {"AND_INVERTED", 4},
    {"NO_OP", 5},
    {"XOR", 6},
    {"OR", 7},
    {"NOR", 8},
    {"EQUIVALENT", 9},
    {"INVERT", 10},
    {"OR_REVERSE", 11},
    {"COPY_INVERTED", 12},
    {"OR_INVERTED", 13},
    {"NAND", 14},
    {"SET", 15},
};
constexpr const EnumValueSet VkInternalAllocationTypeSets[] = {
    {"EXECUTABLE", 0},
};
constexpr const EnumValueSet VkSystemAllocationScopeSets[] = {
    {"COMMAND", 0}, {"OBJECT", 1}, {"CACHE", 2}, {"DEVICE", 3}, {"INSTANCE", 4},
};
constexpr const EnumValueSet VkPhysicalDeviceTypeSets[] = {
    {"OTHER", 0}, {"INTEGRATED_GPU", 1}, {"DISCRETE_GPU", 2}, {"VIRTUAL_GPU", 3}, {"CPU", 4},
};
constexpr const EnumValueSet VkVertexInputRateSets[] = {
    {"VERTEX", 0},
    {"INSTANCE", 1},
};
constexpr const EnumValueSet VkFormatSets[] = {
    {"UNDEFINED", 0},
    {"R4G4_UNORM_PACK8", 1},
    {"R4G4B4A4_UNORM_PACK16", 2},
    {"B4G4R4A4_UNORM_PACK16", 3},
    {"R5G6B5_UNORM_PACK16", 4},
    {"B5G6R5_UNORM_PACK16", 5},
    {"R5G5B5A1_UNORM_PACK16", 6},
    {"B5G5R5A1_UNORM_PACK16", 7},
    {"A1R5G5B5_UNORM_PACK16", 8},
    {"R8_UNORM", 9},
    {"R8_SNORM", 10},
    {"R8_USCALED", 11},
    {"R8_SSCALED", 12},
    {"R8_UINT", 13},
    {"R8_SINT", 14},
    {"R8_SRGB", 15},
    {"R8G8_UNORM", 16},
    {"R8G8_SNORM", 17},
    {"R8G8_USCALED", 18},
    {"R8G8_SSCALED", 19},
    {"R8G8_UINT", 20},
    {"R8G8_SINT", 21},
    {"R8G8_SRGB", 22},
    {"R8G8B8_UNORM", 23},
    {"R8G8B8_SNORM", 24},
    {"R8G8B8_USCALED", 25},
    {"R8G8B8_SSCALED", 26},
    {"R8G8B8_UINT", 27},
    {"R8G8B8_SINT", 28},
    {"R8G8B8_SRGB", 29},
    {"B8G8R8_UNORM", 30},
    {"B8G8R8_SNORM", 31},
    {"B8G8R8_USCALED", 32},
    {"B8G8R8_SSCALED", 33},
    {"B8G8R8_UINT", 34},
    {"B8G8R8_SINT", 35},
    {"B8G8R8_SRGB", 36},
    {"R8G8B8A8_UNORM", 37},
    {"R8G8B8A8_SNORM", 38},
    {"R8G8B8A8_USCALED", 39},
    {"R8G8B8A8_SSCALED", 40},
    {"R8G8B8A8_UINT", 41},
    {"R8G8B8A8_SINT", 42},
    {"R8G8B8A8_SRGB", 43},
    {"B8G8R8A8_UNORM", 44},
    {"B8G8R8A8_SNORM", 45},
    {"B8G8R8A8_USCALED", 46},
    {"B8G8R8A8_SSCALED", 47},
    {"B8G8R8A8_UINT", 48},
    {"B8G8R8A8_SINT", 49},
    {"B8G8R8A8_SRGB", 50},
    {"A8B8G8R8_UNORM_PACK32", 51},
    {"A8B8G8R8_SNORM_PACK32", 52},
    {"A8B8G8R8_USCALED_PACK32", 53},
    {"A8B8G8R8_SSCALED_PACK32", 54},
    {"A8B8G8R8_UINT_PACK32", 55},
    {"A8B8G8R8_SINT_PACK32", 56},
    {"A8B8G8R8_SRGB_PACK32", 57},
    {"A2R10G10B10_UNORM_PACK32", 58},
    {"A2R10G10B10_SNORM_PACK32", 59},
    {"A2R10G10B10_USCALED_PACK32", 60},
    {"A2R10G10B10_SSCALED_PACK32", 61},
    {"A2R10G10B10_UINT_PACK32", 62},
    {"A2R10G10B10_SINT_PACK32", 63},
    {"A2B10G10R10_UNORM_PACK32", 64},
    {"A2B10G10R10_SNORM_PACK32", 65},
    {"A2B10G10R10_USCALED_PACK32", 66},
    {"A2B10G10R10_SSCALED_PACK32", 67},
    {"A2B10G10R10_UINT_PACK32", 68},
    {"A2B10G10R10_SINT_PACK32", 69},
    {"R16_UNORM", 70},
    {"R16_SNORM", 71},
    {"R16_USCALED", 72},
    {"R16_SSCALED", 73},
    {"R16_UINT", 74},
    {"R16_SINT", 75},
    {"R16_SFLOAT", 76},
    {"R16G16_UNORM", 77},
    {"R16G16_SNORM", 78},
    {"R16G16_USCALED", 79},
    {"R16G16_SSCALED", 80},
    {"R16G16_UINT", 81},
    {"R16G16_SINT", 82},
    {"R16G16_SFLOAT", 83},
    {"R16G16B16_UNORM", 84},
    {"R16G16B16_SNORM", 85},
    {"R16G16B16_USCALED", 86},
    {"R16G16B16_SSCALED", 87},
    {"R16G16B16_UINT", 88},
    {"R16G16B16_SINT", 89},
    {"R16G16B16_SFLOAT", 90},
    {"R16G16B16A16_UNORM", 91},
    {"R16G16B16A16_SNORM", 92},
    {"R16G16B16A16_USCALED", 93},
    {"R16G16B16A16_SSCALED", 94},
    {"R16G16B16A16_UINT", 95},
    {"R16G16B16A16_SINT", 96},
    {"R16G16B16A16_SFLOAT", 97},
    {"R32_UINT", 98},
    {"R32_SINT", 99},
    {"R32_SFLOAT", 100},
    {"R32G32_UINT", 101},
    {"R32G32_SINT", 102},
    {"R32G32_SFLOAT", 103},
    {"R32G32B32_UINT", 104},
    {"R32G32B32_SINT", 105},
    {"R32G32B32_SFLOAT", 106},
    {"R32G32B32A32_UINT", 107},
    {"R32G32B32A32_SINT", 108},
    {"R32G32B32A32_SFLOAT", 109},
    {"R64_UINT", 110},
    {"R64_SINT", 111},
    {"R64_SFLOAT", 112},
    {"R64G64_UINT", 113},
    {"R64G64_SINT", 114},
    {"R64G64_SFLOAT", 115},
    {"R64G64B64_UINT", 116},
    {"R64G64B64_SINT", 117},
    {"R64G64B64_SFLOAT", 118},
    {"R64G64B64A64_UINT", 119},
    {"R64G64B64A64_SINT", 120},
    {"R64G64B64A64_SFLOAT", 121},
    {"B10G11R11_UFLOAT_PACK32", 122},
    {"E5B9G9R9_UFLOAT_PACK32", 123},
    {"D16_UNORM", 124},
    {"X8_D24_UNORM_PACK32", 125},
    {"D32_SFLOAT", 126},
    {"S8_UINT", 127},
    {"D16_UNORM_S8_UINT", 128},
    {"D24_UNORM_S8_UINT", 129},
    {"D32_SFLOAT_S8_UINT", 130},
    {"BC1_RGB_UNORM_BLOCK", 131},
    {"BC1_RGB_SRGB_BLOCK", 132},
    {"BC1_RGBA_UNORM_BLOCK", 133},
    {"BC1_RGBA_SRGB_BLOCK", 134},
    {"BC2_UNORM_BLOCK", 135},
    {"BC2_SRGB_BLOCK", 136},
    {"BC3_UNORM_BLOCK", 137},
    {"BC3_SRGB_BLOCK", 138},
    {"BC4_UNORM_BLOCK", 139},
    {"BC4_SNORM_BLOCK", 140},
    {"BC5_UNORM_BLOCK", 141},
    {"BC5_SNORM_BLOCK", 142},
    {"BC6H_UFLOAT_BLOCK", 143},
    {"BC6H_SFLOAT_BLOCK", 144},
    {"BC7_UNORM_BLOCK", 145},
    {"BC7_SRGB_BLOCK", 146},
    {"ETC2_R8G8B8_UNORM_BLOCK", 147},
    {"ETC2_R8G8B8_SRGB_BLOCK", 148},
    {"ETC2_R8G8B8A1_UNORM_BLOCK", 149},
    {"ETC2_R8G8B8A1_SRGB_BLOCK", 150},
    {"ETC2_R8G8B8A8_UNORM_BLOCK", 151},
    {"ETC2_R8G8B8A8_SRGB_BLOCK", 152},
    {"EAC_R11_UNORM_BLOCK", 153},
    {"EAC_R11_SNORM_BLOCK", 154},
    {"EAC_R11G11_UNORM_BLOCK", 155},
    {"EAC_R11G11_SNORM_BLOCK", 156},
    {"ASTC_4x4_UNORM_BLOCK", 157},
    {"ASTC_4x4_SRGB_BLOCK", 158},
    {"ASTC_5x4_UNORM_BLOCK", 159},
    {"ASTC_5x4_SRGB_BLOCK", 160},
    {"ASTC_5x5_UNORM_BLOCK", 161},
    {"ASTC_5x5_SRGB_BLOCK", 162},
    {"ASTC_6x5_UNORM_BLOCK", 163},
    {"ASTC_6x5_SRGB_BLOCK", 164},
    {"ASTC_6x6_UNORM_BLOCK", 165},
    {"ASTC_6x6_SRGB_BLOCK", 166},
    {"ASTC_8x5_UNORM_BLOCK", 167},
    {"ASTC_8x5_SRGB_BLOCK", 168},
    {"ASTC_8x6_UNORM_BLOCK", 169},
    {"ASTC_8x6_SRGB_BLOCK", 170},
    {"ASTC_8x8_UNORM_BLOCK", 171},
    {"ASTC_8x8_SRGB_BLOCK", 172},
    {"ASTC_10x5_UNORM_BLOCK", 173},
    {"ASTC_10x5_SRGB_BLOCK", 174},
    {"ASTC_10x6_UNORM_BLOCK", 175},
    {"ASTC_10x6_SRGB_BLOCK", 176},
    {"ASTC_10x8_UNORM_BLOCK", 177},
    {"ASTC_10x8_SRGB_BLOCK", 178},
    {"ASTC_10x10_UNORM_BLOCK", 179},
    {"ASTC_10x10_SRGB_BLOCK", 180},
    {"ASTC_12x10_UNORM_BLOCK", 181},
    {"ASTC_12x10_SRGB_BLOCK", 182},
    {"ASTC_12x12_UNORM_BLOCK", 183},
    {"ASTC_12x12_SRGB_BLOCK", 184},
};
constexpr const EnumValueSet VkStructureTypeSets[] = {
    {"APPLICATION_INFO", 0},
    {"INSTANCE_CREATE_INFO", 1},
    {"DEVICE_QUEUE_CREATE_INFO", 2},
    {"DEVICE_CREATE_INFO", 3},
    {"SUBMIT_INFO", 4},
    {"MEMORY_ALLOCATE_INFO", 5},
    {"MAPPED_MEMORY_RANGE", 6},
    {"BIND_SPARSE_INFO", 7},
    {"FENCE_CREATE_INFO", 8},
    {"SEMAPHORE_CREATE_INFO", 9},
    {"EVENT_CREATE_INFO", 10},
    {"QUERY_POOL_CREATE_INFO", 11},
    {"BUFFER_CREATE_INFO", 12},
    {"BUFFER_VIEW_CREATE_INFO", 13},
    {"IMAGE_CREATE_INFO", 14},
    {"IMAGE_VIEW_CREATE_INFO", 15},
    {"SHADER_MODULE_CREATE_INFO", 16},
    {"PIPELINE_CACHE_CREATE_INFO", 17},
    {"PIPELINE_SHADER_STAGE_CREATE_INFO", 18},
    {"PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO", 19},
    {"PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO", 20},
    {"PIPELINE_TESSELLATION_STATE_CREATE_INFO", 21},
    {"PIPELINE_VIEWPORT_STATE_CREATE_INFO", 22},
    {"PIPELINE_RASTERIZATION_STATE_CREATE_INFO", 23},
    {"PIPELINE_MULTISAMPLE_STATE_CREATE_INFO", 24},
    {"PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO", 25},
    {"PIPELINE_COLOR_BLEND_STATE_CREATE_INFO", 26},
    {"PIPELINE_DYNAMIC_STATE_CREATE_INFO", 27},
    {"GRAPHICS_PIPELINE_CREATE_INFO", 28},
    {"COMPUTE_PIPELINE_CREATE_INFO", 29},
    {"PIPELINE_LAYOUT_CREATE_INFO", 30},
    {"SAMPLER_CREATE_INFO", 31},
    {"DESCRIPTOR_SET_LAYOUT_CREATE_INFO", 32},
    {"DESCRIPTOR_POOL_CREATE_INFO", 33},
    {"DESCRIPTOR_SET_ALLOCATE_INFO", 34},
    {"WRITE_DESCRIPTOR_SET", 35},
    {"COPY_DESCRIPTOR_SET", 36},
    {"FRAMEBUFFER_CREATE_INFO", 37},
    {"RENDER_PASS_CREATE_INFO", 38},
    {"COMMAND_POOL_CREATE_INFO", 39},
    {"COMMAND_BUFFER_ALLOCATE_INFO", 40},
    {"COMMAND_BUFFER_INHERITANCE_INFO", 41},
    {"COMMAND_BUFFER_BEGIN_INFO", 42},
    {"RENDER_PASS_BEGIN_INFO", 43},
    {"BUFFER_MEMORY_BARRIER", 44},
    {"IMAGE_MEMORY_BARRIER", 45},
    {"MEMORY_BARRIER", 46},
    {"LOADER_INSTANCE_CREATE_INFO", 47},
    {"LOADER_DEVICE_CREATE_INFO", 48},
};
constexpr const EnumValueSet VkSubpassContentsSets[] = {
    {"INLINE", 0},
    {"SECONDARY_COMMAND_BUFFERS", 1},
};
constexpr const EnumValueSet VkDynamicStateSets[] = {
    {"VIEWPORT", 0},
    {"SCISSOR", 1},
    {"LINE_WIDTH", 2},
    {"DEPTH_BIAS", 3},
    {"BLEND_CONSTANTS", 4},
    {"DEPTH_BOUNDS", 5},
    {"STENCIL_COMPARE_MASK", 6},
    {"STENCIL_WRITE_MASK", 7},
    {"STENCIL_REFERENCE", 8},
};
constexpr const EnumValueSet VkDescriptorUpdateTemplateTypeSets[] = {
    {"DESCRIPTOR_SET", 0},
};
constexpr const EnumValueSet VkObjectTypeSets[] = {
    {"UNKNOWN", 0},
    {"INSTANCE", 1},
    {"PHYSICAL_DEVICE", 2},
    {"DEVICE", 3},
    {"QUEUE", 4},
    {"SEMAPHORE", 5},
    {"COMMAND_BUFFER", 6},
    {"FENCE", 7},
    {"DEVICE_MEMORY", 8},
    {"BUFFER", 9},
    {"IMAGE", 10},
    {"EVENT", 11},
    {"QUERY_POOL", 12},
    {"BUFFER_VIEW", 13},
    {"IMAGE_VIEW", 14},
    {"SHADER_MODULE", 15},
    {"PIPELINE_CACHE", 16},
    {"PIPELINE_LAYOUT", 17},
    {"RENDER_PASS", 18},
    {"PIPELINE", 19},
    {"DESCRIPTOR_SET_LAYOUT", 20},
    {"SAMPLER", 21},
    {"DESCRIPTOR_POOL", 22},
    {"DESCRIPTOR_SET", 23},
    {"FRAMEBUFFER", 24},
    {"COMMAND_POOL", 25},
};
constexpr const EnumValueSet VkQueueFlagBitsSets[] = {
    {"GRAPHICS_BIT", 0x00000001},
    {"COMPUTE_BIT", 0x00000002},
    {"TRANSFER_BIT", 0x00000004},
    {"SPARSE_BINDING_BIT", 0x00000008},
};
constexpr const EnumValueSet VkRenderPassCreateFlagBitsSets[] = {};
constexpr const EnumValueSet VkDeviceQueueCreateFlagBitsSets[] = {};
constexpr const EnumValueSet VkMemoryPropertyFlagBitsSets[] = {
    {"DEVICE_LOCAL_BIT", 0x00000001},     {"HOST_VISIBLE_BIT", 0x00000002},
    {"HOST_COHERENT_BIT", 0x00000004},    {"HOST_CACHED_BIT", 0x00000008},
    {"LAZILY_ALLOCATED_BIT", 0x00000010},
};
constexpr const EnumValueSet VkMemoryHeapFlagBitsSets[] = {
    {"DEVICE_LOCAL_BIT", 0x00000001},
};
constexpr const EnumValueSet VkAccessFlagBitsSets[] = {
    {"INDIRECT_COMMAND_READ_BIT", 0x00000001},
    {"INDEX_READ_BIT", 0x00000002},
    {"VERTEX_ATTRIBUTE_READ_BIT", 0x00000004},
    {"UNIFORM_READ_BIT", 0x00000008},
    {"INPUT_ATTACHMENT_READ_BIT", 0x00000010},
    {"SHADER_READ_BIT", 0x00000020},
    {"SHADER_WRITE_BIT", 0x00000040},
    {"COLOR_ATTACHMENT_READ_BIT", 0x00000080},
    {"COLOR_ATTACHMENT_WRITE_BIT", 0x00000100},
    {"DEPTH_STENCIL_ATTACHMENT_READ_BIT", 0x00000200},
    {"DEPTH_STENCIL_ATTACHMENT_WRITE_BIT", 0x00000400},
    {"TRANSFER_READ_BIT", 0x00000800},
    {"TRANSFER_WRITE_BIT", 0x00001000},
    {"HOST_READ_BIT", 0x00002000},
    {"HOST_WRITE_BIT", 0x00004000},
    {"MEMORY_READ_BIT", 0x00008000},
    {"MEMORY_WRITE_BIT", 0x00010000},
};
constexpr const EnumValueSet VkBufferUsageFlagBitsSets[] = {
    {"TRANSFER_SRC_BIT", 0x00000001},         {"TRANSFER_DST_BIT", 0x00000002},
    {"UNIFORM_TEXEL_BUFFER_BIT", 0x00000004}, {"STORAGE_TEXEL_BUFFER_BIT", 0x00000008},
    {"UNIFORM_BUFFER_BIT", 0x00000010},       {"STORAGE_BUFFER_BIT", 0x00000020},
    {"INDEX_BUFFER_BIT", 0x00000040},         {"VERTEX_BUFFER_BIT", 0x00000080},
    {"INDIRECT_BUFFER_BIT", 0x00000100},
};
constexpr const EnumValueSet VkBufferCreateFlagBitsSets[] = {
    {"SPARSE_BINDING_BIT", 0x00000001},
    {"SPARSE_RESIDENCY_BIT", 0x00000002},
    {"SPARSE_ALIASED_BIT", 0x00000004},
};
constexpr const EnumValueSet VkShaderStageFlagBitsSets[] = {
    {"VERTEX_BIT", 0x00000001},
    {"TESSELLATION_CONTROL_BIT", 0x00000002},
    {"TESSELLATION_EVALUATION_BIT", 0x00000004},
    {"GEOMETRY_BIT", 0x00000008},
    {"FRAGMENT_BIT", 0x00000010},
    {"COMPUTE_BIT", 0x00000020},
    {"ALL_GRAPHICS", 0x0000001F},
    {"ALL", 0x7FFFFFFF},
};
constexpr const EnumValueSet VkImageUsageFlagBitsSets[] = {
    {"TRANSFER_SRC_BIT", 0x00000001},
    {"TRANSFER_DST_BIT", 0x00000002},
    {"SAMPLED_BIT", 0x00000004},
    {"STORAGE_BIT", 0x00000008},
    {"COLOR_ATTACHMENT_BIT", 0x00000010},
    {"DEPTH_STENCIL_ATTACHMENT_BIT", 0x00000020},
    {"TRANSIENT_ATTACHMENT_BIT", 0x00000040},
    {"INPUT_ATTACHMENT_BIT", 0x00000080},
};
constexpr const EnumValueSet VkImageCreateFlagBitsSets[] = {
    {"SPARSE_BINDING_BIT", 0x00000001},  {"SPARSE_RESIDENCY_BIT", 0x00000002},
    {"SPARSE_ALIASED_BIT", 0x00000004},  {"MUTABLE_FORMAT_BIT", 0x00000008},
    {"CUBE_COMPATIBLE_BIT", 0x00000010},
};
constexpr const EnumValueSet VkImageViewCreateFlagBitsSets[] = {};
constexpr const EnumValueSet VkSamplerCreateFlagBitsSets[] = {};
constexpr const EnumValueSet VkPipelineCreateFlagBitsSets[] = {
    {"DISABLE_OPTIMIZATION_BIT", 0x00000001},
    {"ALLOW_DERIVATIVES_BIT", 0x00000002},
    {"DERIVATIVE_BIT", 0x00000004},
};
constexpr const EnumValueSet VkPipelineShaderStageCreateFlagBitsSets[] = {};
constexpr const EnumValueSet VkColorComponentFlagBitsSets[] = {
    {"R_BIT", 0x00000001},
    {"G_BIT", 0x00000002},
    {"B_BIT", 0x00000004},
    {"A_BIT", 0x00000008},
};
constexpr const EnumValueSet VkFenceCreateFlagBitsSets[] = {
    {"SIGNALED_BIT", 0x00000001},
};
constexpr const EnumValueSet VkSemaphoreCreateFlagBitsSets[] = {};
constexpr const EnumValueSet VkFormatFeatureFlagBitsSets[] = {
    {"SAMPLED_IMAGE_BIT", 0x00000001},
    {"STORAGE_IMAGE_BIT", 0x00000002},
    {"STORAGE_IMAGE_ATOMIC_BIT", 0x00000004},
    {"UNIFORM_TEXEL_BUFFER_BIT", 0x00000008},
    {"STORAGE_TEXEL_BUFFER_BIT", 0x00000010},
    {"STORAGE_TEXEL_BUFFER_ATOMIC_BIT", 0x00000020},
    {"VERTEX_BUFFER_BIT", 0x00000040},
    {"COLOR_ATTACHMENT_BIT", 0x00000080},
    {"COLOR_ATTACHMENT_BLEND_BIT", 0x00000100},
    {"DEPTH_STENCIL_ATTACHMENT_BIT", 0x00000200},
    {"BLIT_SRC_BIT", 0x00000400},
    {"BLIT_DST_BIT", 0x00000800},
    {"SAMPLED_IMAGE_FILTER_LINEAR_BIT", 0x00001000},
};
constexpr const EnumValueSet VkQueryControlFlagBitsSets[] = {
    {"PRECISE_BIT", 0x00000001},
};
constexpr const EnumValueSet VkQueryResultFlagBitsSets[] = {
    {"64_BIT", 0x00000001},
    {"WAIT_BIT", 0x00000002},
    {"WITH_AVAILABILITY_BIT", 0x00000004},
    {"PARTIAL_BIT", 0x00000008},
};
constexpr const EnumValueSet VkCommandBufferUsageFlagBitsSets[] = {
    {"ONE_TIME_SUBMIT_BIT", 0x00000001},
    {"RENDER_PASS_CONTINUE_BIT", 0x00000002},
    {"SIMULTANEOUS_USE_BIT", 0x00000004},
};
constexpr const EnumValueSet VkQueryPipelineStatisticFlagBitsSets[] = {
    {"INPUT_ASSEMBLY_VERTICES_BIT", 0x00000001},
    {"INPUT_ASSEMBLY_PRIMITIVES_BIT", 0x00000002},
    {"VERTEX_SHADER_INVOCATIONS_BIT", 0x00000004},
    {"GEOMETRY_SHADER_INVOCATIONS_BIT", 0x00000008},
    {"GEOMETRY_SHADER_PRIMITIVES_BIT", 0x00000010},
    {"CLIPPING_INVOCATIONS_BIT", 0x00000020},
    {"CLIPPING_PRIMITIVES_BIT", 0x00000040},
    {"FRAGMENT_SHADER_INVOCATIONS_BIT", 0x00000080},
    {"TESSELLATION_CONTROL_SHADER_PATCHES_BIT", 0x00000100},
    {"TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT", 0x00000200},
    {"COMPUTE_SHADER_INVOCATIONS_BIT", 0x00000400},
};
constexpr const EnumValueSet VkImageAspectFlagBitsSets[] = {
    {"COLOR_BIT", 0x00000001},
    {"DEPTH_BIT", 0x00000002},
    {"STENCIL_BIT", 0x00000004},
    {"METADATA_BIT", 0x00000008},
};
constexpr const EnumValueSet VkSparseImageFormatFlagBitsSets[] = {
    {"SINGLE_MIPTAIL_BIT", 0x00000001},
    {"ALIGNED_MIP_SIZE_BIT", 0x00000002},
    {"NONSTANDARD_BLOCK_SIZE_BIT", 0x00000004},
};
constexpr const EnumValueSet VkSparseMemoryBindFlagBitsSets[] = {
    {"METADATA_BIT", 0x00000001},
};
constexpr const EnumValueSet VkPipelineStageFlagBitsSets[] = {
    {"TOP_OF_PIPE_BIT", 0x00000001},
    {"DRAW_INDIRECT_BIT", 0x00000002},
    {"VERTEX_INPUT_BIT", 0x00000004},
    {"VERTEX_SHADER_BIT", 0x00000008},
    {"TESSELLATION_CONTROL_SHADER_BIT", 0x00000010},
    {"TESSELLATION_EVALUATION_SHADER_BIT", 0x00000020},
    {"GEOMETRY_SHADER_BIT", 0x00000040},
    {"FRAGMENT_SHADER_BIT", 0x00000080},
    {"EARLY_FRAGMENT_TESTS_BIT", 0x00000100},
    {"LATE_FRAGMENT_TESTS_BIT", 0x00000200},
    {"COLOR_ATTACHMENT_OUTPUT_BIT", 0x00000400},
    {"COMPUTE_SHADER_BIT", 0x00000800},
    {"TRANSFER_BIT", 0x00001000},
    {"BOTTOM_OF_PIPE_BIT", 0x00002000},
    {"HOST_BIT", 0x00004000},
    {"ALL_GRAPHICS_BIT", 0x00008000},
    {"ALL_COMMANDS_BIT", 0x00010000},
};
constexpr const EnumValueSet VkCommandPoolCreateFlagBitsSets[] = {
    {"TRANSIENT_BIT", 0x00000001},
    {"RESET_COMMAND_BUFFER_BIT", 0x00000002},
};
constexpr const EnumValueSet VkCommandPoolResetFlagBitsSets[] = {
    {"RELEASE_RESOURCES_BIT", 0x00000001},
};
constexpr const EnumValueSet VkCommandBufferResetFlagBitsSets[] = {
    {"RELEASE_RESOURCES_BIT", 0x00000001},
};
constexpr const EnumValueSet VkSampleCountFlagBitsSets[] = {
    {"1_BIT", 0x00000001},  {"2_BIT", 0x00000002},  {"4_BIT", 0x00000004},  {"8_BIT", 0x00000008},
    {"16_BIT", 0x00000010}, {"32_BIT", 0x00000020}, {"64_BIT", 0x00000040},
};
constexpr const EnumValueSet VkAttachmentDescriptionFlagBitsSets[] = {
    {"MAY_ALIAS_BIT", 0x00000001},
};
constexpr const EnumValueSet VkStencilFaceFlagBitsSets[] = {
    {"FRONT_BIT", 0x00000001},
    {"BACK_BIT", 0x00000002},
    {"FRONT_AND_BACK", 0x00000003},
    {"VK_STENCIL_FRONT_AND_BACK", 0x00000003},
};
constexpr const EnumValueSet VkDescriptorPoolCreateFlagBitsSets[] = {
    {"FREE_DESCRIPTOR_SET_BIT", 0x00000001},
};
constexpr const EnumValueSet VkDependencyFlagBitsSets[] = {
    {"BY_REGION_BIT", 0x00000001},
};
constexpr const EnumValueSet VkSemaphoreTypeSets[] = {
    {"BINARY", 0},
    {"TIMELINE", 1},
};
constexpr const EnumValueSet VkSemaphoreWaitFlagBitsSets[] = {
    {"ANY_BIT", 0x00000001},
};
constexpr const EnumValueSet VkPresentModeKHRSets[] = {
    {"IMMEDIATE_KHR", 0},
    {"MAILBOX_KHR", 1},
    {"FIFO_KHR", 2},
    {"FIFO_RELAXED_KHR", 3},
};
constexpr const EnumValueSet VkColorSpaceKHRSets[] = {
    {"SRGB_NONLINEAR_KHR", 0},
    {"VK_COLORSPACE_SRGB_NONLINEAR_KHR", 0},
};
constexpr const EnumValueSet VkDisplayPlaneAlphaFlagBitsKHRSets[] = {
    {"OPAQUE_BIT_KHR", 0x00000001},
    {"GLOBAL_BIT_KHR", 0x00000002},
    {"PER_PIXEL_BIT_KHR", 0x00000004},
    {"PER_PIXEL_PREMULTIPLIED_BIT_KHR", 0x00000008},
};
constexpr const EnumValueSet VkCompositeAlphaFlagBitsKHRSets[] = {
    {"OPAQUE_BIT_KHR", 0x00000001},
    {"PRE_MULTIPLIED_BIT_KHR", 0x00000002},
    {"POST_MULTIPLIED_BIT_KHR", 0x00000004},
    {"INHERIT_BIT_KHR", 0x00000008},
};
constexpr const EnumValueSet VkSurfaceTransformFlagBitsKHRSets[] = {
    {"IDENTITY_BIT_KHR", 0x00000001},
    {"ROTATE_90_BIT_KHR", 0x00000002},
    {"ROTATE_180_BIT_KHR", 0x00000004},
    {"ROTATE_270_BIT_KHR", 0x00000008},
    {"HORIZONTAL_MIRROR_BIT_KHR", 0x00000010},
    {"HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR", 0x00000020},
    {"HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR", 0x00000040},
    {"HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR", 0x00000080},
    {"INHERIT_BIT_KHR", 0x00000100},
};
constexpr const EnumValueSet VkSwapchainImageUsageFlagBitsANDROIDSets[] = {
    {"SHARED_BIT_ANDROID", 0x00000001},
};
constexpr const EnumValueSet VkTimeDomainEXTSets[] = {
    {"DEVICE_EXT", 0},
    {"CLOCK_MONOTONIC_EXT", 1},
    {"CLOCK_MONOTONIC_RAW_EXT", 2},
    {"QUERY_PERFORMANCE_COUNTER_EXT", 3},
};
constexpr const EnumValueSet VkDebugReportFlagBitsEXTSets[] = {
    {"INFORMATION_BIT_EXT", 0x00000001},
    {"WARNING_BIT_EXT", 0x00000002},
    {"PERFORMANCE_WARNING_BIT_EXT", 0x00000004},
    {"ERROR_BIT_EXT", 0x00000008},
    {"DEBUG_BIT_EXT", 0x00000010},
};
constexpr const EnumValueSet VkDebugReportObjectTypeEXTSets[] = {
    {"UNKNOWN_EXT", 0},
    {"INSTANCE_EXT", 1},
    {"PHYSICAL_DEVICE_EXT", 2},
    {"DEVICE_EXT", 3},
    {"QUEUE_EXT", 4},
    {"SEMAPHORE_EXT", 5},
    {"COMMAND_BUFFER_EXT", 6},
    {"FENCE_EXT", 7},
    {"DEVICE_MEMORY_EXT", 8},
    {"BUFFER_EXT", 9},
    {"IMAGE_EXT", 10},
    {"EVENT_EXT", 11},
    {"QUERY_POOL_EXT", 12},
    {"BUFFER_VIEW_EXT", 13},
    {"IMAGE_VIEW_EXT", 14},
    {"SHADER_MODULE_EXT", 15},
    {"PIPELINE_CACHE_EXT", 16},
    {"PIPELINE_LAYOUT_EXT", 17},
    {"RENDER_PASS_EXT", 18},
    {"PIPELINE_EXT", 19},
    {"DESCRIPTOR_SET_LAYOUT_EXT", 20},
    {"SAMPLER_EXT", 21},
    {"DESCRIPTOR_POOL_EXT", 22},
    {"DESCRIPTOR_SET_EXT", 23},
    {"FRAMEBUFFER_EXT", 24},
    {"COMMAND_POOL_EXT", 25},
    {"SURFACE_KHR_EXT", 26},
    {"SWAPCHAIN_KHR_EXT", 27},
    {"DEBUG_REPORT_CALLBACK_EXT_EXT", 28},
    {"DEBUG_REPORT_EXT", 28},
    {"DISPLAY_KHR_EXT", 29},
    {"DISPLAY_MODE_KHR_EXT", 30},
    {"OBJECT_TABLE_NVX_EXT", 31},
    {"INDIRECT_COMMANDS_LAYOUT_NVX_EXT", 32},
    {"VALIDATION_CACHE_EXT_EXT", 33},
    {"VALIDATION_CACHE_EXT", 33},
};
constexpr const EnumValueSet VkRasterizationOrderAMDSets[] = {
    {"STRICT_AMD", 0},
    {"RELAXED_AMD", 1},
};
constexpr const EnumValueSet VkExternalMemoryHandleTypeFlagBitsNVSets[] = {
    {"OPAQUE_WIN32_BIT_NV", 0x00000001},
    {"OPAQUE_WIN32_KMT_BIT_NV", 0x00000002},
    {"D3D11_IMAGE_BIT_NV", 0x00000004},
    {"D3D11_IMAGE_KMT_BIT_NV", 0x00000008},
};
constexpr const EnumValueSet VkExternalMemoryFeatureFlagBitsNVSets[] = {
    {"DEDICATED_ONLY_BIT_NV", 0x00000001},
    {"EXPORTABLE_BIT_NV", 0x00000002},
    {"IMPORTABLE_BIT_NV", 0x00000004},
};
constexpr const EnumValueSet VkValidationCheckEXTSets[] = {
    {"ALL_EXT", 0},
    {"SHADERS_EXT", 1},
};
constexpr const EnumValueSet VkValidationFeatureEnableEXTSets[] = {
    {"GPU_ASSISTED_EXT", 0},
    {"GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT", 1},
    {"BEST_PRACTICES_EXT", 2},
};
constexpr const EnumValueSet VkValidationFeatureDisableEXTSets[] = {
    {"ALL_EXT", 0},
    {"SHADERS_EXT", 1},
    {"THREAD_SAFETY_EXT", 2},
    {"API_PARAMETERS_EXT", 3},
    {"OBJECT_LIFETIMES_EXT", 4},
    {"CORE_CHECKS_EXT", 5},
    {"UNIQUE_HANDLES_EXT", 6},
};
constexpr const EnumValueSet VkSubgroupFeatureFlagBitsSets[] = {
    {"BASIC_BIT", 0x00000001},      {"VOTE_BIT", 0x00000002},
    {"ARITHMETIC_BIT", 0x00000004}, {"BALLOT_BIT", 0x00000008},
    {"SHUFFLE_BIT", 0x00000010},    {"SHUFFLE_RELATIVE_BIT", 0x00000020},
    {"CLUSTERED_BIT", 0x00000040},  {"QUAD_BIT", 0x00000080},
};
constexpr const EnumValueSet VkIndirectCommandsLayoutUsageFlagBitsNVXSets[] = {
    {"UNORDERED_SEQUENCES_BIT_NVX", 0x00000001},
    {"SPARSE_SEQUENCES_BIT_NVX", 0x00000002},
    {"EMPTY_EXECUTIONS_BIT_NVX", 0x00000004},
    {"INDEXED_SEQUENCES_BIT_NVX", 0x00000008},
};
constexpr const EnumValueSet VkObjectEntryUsageFlagBitsNVXSets[] = {
    {"GRAPHICS_BIT_NVX", 0x00000001},
    {"COMPUTE_BIT_NVX", 0x00000002},
};
constexpr const EnumValueSet VkIndirectCommandsTokenTypeNVXSets[] = {
    {"PIPELINE_NVX", 0},      {"DESCRIPTOR_SET_NVX", 1}, {"INDEX_BUFFER_NVX", 2},
    {"VERTEX_BUFFER_NVX", 3}, {"PUSH_CONSTANT_NVX", 4},  {"DRAW_INDEXED_NVX", 5},
    {"DRAW_NVX", 6},          {"DISPATCH_NVX", 7},
};
constexpr const EnumValueSet VkObjectEntryTypeNVXSets[] = {
    {"DESCRIPTOR_SET_NVX", 0}, {"PIPELINE_NVX", 1},      {"INDEX_BUFFER_NVX", 2},
    {"VERTEX_BUFFER_NVX", 3},  {"PUSH_CONSTANT_NVX", 4},
};
constexpr const EnumValueSet VkDescriptorSetLayoutCreateFlagBitsSets[] = {};
constexpr const EnumValueSet VkExternalMemoryHandleTypeFlagBitsSets[] = {
    {"OPAQUE_FD_BIT", 0x00000001},         {"OPAQUE_WIN32_BIT", 0x00000002},
    {"OPAQUE_WIN32_KMT_BIT", 0x00000004},  {"D3D11_TEXTURE_BIT", 0x00000008},
    {"D3D11_TEXTURE_KMT_BIT", 0x00000010}, {"D3D12_HEAP_BIT", 0x00000020},
    {"D3D12_RESOURCE_BIT", 0x00000040},
};
constexpr const EnumValueSet VkExternalMemoryFeatureFlagBitsSets[] = {
    {"DEDICATED_ONLY_BIT", 0x00000001},
    {"EXPORTABLE_BIT", 0x00000002},
    {"IMPORTABLE_BIT", 0x00000004},
};
constexpr const EnumValueSet VkExternalSemaphoreHandleTypeFlagBitsSets[] = {
    {"OPAQUE_FD_BIT", 0x00000001},        {"OPAQUE_WIN32_BIT", 0x00000002},
    {"OPAQUE_WIN32_KMT_BIT", 0x00000004}, {"D3D12_FENCE_BIT", 0x00000008},
    {"SYNC_FD_BIT", 0x00000010},
};
constexpr const EnumValueSet VkExternalSemaphoreFeatureFlagBitsSets[] = {
    {"EXPORTABLE_BIT", 0x00000001},
    {"IMPORTABLE_BIT", 0x00000002},
};
constexpr const EnumValueSet VkSemaphoreImportFlagBitsSets[] = {
    {"TEMPORARY_BIT", 0x00000001},
};
constexpr const EnumValueSet VkExternalFenceHandleTypeFlagBitsSets[] = {
    {"OPAQUE_FD_BIT", 0x00000001},
    {"OPAQUE_WIN32_BIT", 0x00000002},
    {"OPAQUE_WIN32_KMT_BIT", 0x00000004},
    {"SYNC_FD_BIT", 0x00000008},
};
constexpr const EnumValueSet VkExternalFenceFeatureFlagBitsSets[] = {
    {"EXPORTABLE_BIT", 0x00000001},
    {"IMPORTABLE_BIT", 0x00000002},
};
constexpr const EnumValueSet VkFenceImportFlagBitsSets[] = {
    {"TEMPORARY_BIT", 0x00000001},
};
constexpr const EnumValueSet VkSurfaceCounterFlagBitsEXTSets[] = {
    {"VBLANK_EXT", 0x00000001},
};
constexpr const EnumValueSet VkDisplayPowerStateEXTSets[] = {
    {"OFF_EXT", 0},
    {"SUSPEND_EXT", 1},
    {"ON_EXT", 2},
};
constexpr const EnumValueSet VkDeviceEventTypeEXTSets[] = {
    {"DISPLAY_HOTPLUG_EXT", 0},
};
constexpr const EnumValueSet VkDisplayEventTypeEXTSets[] = {
    {"FIRST_PIXEL_OUT_EXT", 0},
};
constexpr const EnumValueSet VkPeerMemoryFeatureFlagBitsSets[] = {
    {"COPY_SRC_BIT", 0x00000001},
    {"COPY_DST_BIT", 0x00000002},
    {"GENERIC_SRC_BIT", 0x00000004},
    {"GENERIC_DST_BIT", 0x00000008},
};
constexpr const EnumValueSet VkMemoryAllocateFlagBitsSets[] = {
    {"DEVICE_MASK_BIT", 0x00000001},
};
constexpr const EnumValueSet VkDeviceGroupPresentModeFlagBitsKHRSets[] = {
    {"LOCAL_BIT_KHR", 0x00000001},
    {"REMOTE_BIT_KHR", 0x00000002},
    {"SUM_BIT_KHR", 0x00000004},
    {"LOCAL_MULTI_DEVICE_BIT_KHR", 0x00000008},
};
constexpr const EnumValueSet VkSwapchainCreateFlagBitsKHRSets[] = {};
constexpr const EnumValueSet VkViewportCoordinateSwizzleNVSets[] = {
    {"POSITIVE_X_NV", 0}, {"NEGATIVE_X_NV", 1}, {"POSITIVE_Y_NV", 2}, {"NEGATIVE_Y_NV", 3},
    {"POSITIVE_Z_NV", 4}, {"NEGATIVE_Z_NV", 5}, {"POSITIVE_W_NV", 6}, {"NEGATIVE_W_NV", 7},
};
constexpr const EnumValueSet VkDiscardRectangleModeEXTSets[] = {
    {"INCLUSIVE_EXT", 0},
    {"EXCLUSIVE_EXT", 1},
};
constexpr const EnumValueSet VkSubpassDescriptionFlagBitsSets[] = {};
constexpr const EnumValueSet VkPointClippingBehaviorSets[] = {
    {"ALL_CLIP_PLANES", 0},
    {"USER_CLIP_PLANES_ONLY", 1},
};
constexpr const EnumValueSet VkSamplerReductionModeSets[] = {
    {"WEIGHTED_AVERAGE", 0},
    {"MIN", 1},
    {"MAX", 2},
};
constexpr const EnumValueSet VkTessellationDomainOriginSets[] = {
    {"UPPER_LEFT", 0},
    {"LOWER_LEFT", 1},
};
constexpr const EnumValueSet VkSamplerYcbcrModelConversionSets[] = {
    {"RGB_IDENTITY", 0}, {"YCBCR_IDENTITY", 1}, {"YCBCR_709", 2},
    {"YCBCR_601", 3},    {"YCBCR_2020", 4},
};
constexpr const EnumValueSet VkSamplerYcbcrRangeSets[] = {
    {"ITU_FULL", 0},
    {"ITU_NARROW", 1},
};
constexpr const EnumValueSet VkChromaLocationSets[] = {
    {"COSITED_EVEN", 0},
    {"MIDPOINT", 1},
};
constexpr const EnumValueSet VkBlendOverlapEXTSets[] = {
    {"UNCORRELATED_EXT", 0},
    {"DISJOINT_EXT", 1},
    {"CONJOINT_EXT", 2},
};
constexpr const EnumValueSet VkCoverageModulationModeNVSets[] = {
    {"NONE_NV", 0},
    {"RGB_NV", 1},
    {"ALPHA_NV", 2},
    {"RGBA_NV", 3},
};
constexpr const EnumValueSet VkCoverageReductionModeNVSets[] = {
    {"MERGE_NV", 0},
    {"TRUNCATE_NV", 1},
};
constexpr const EnumValueSet VkValidationCacheHeaderVersionEXTSets[] = {
    {"ONE_EXT", 1},
};
constexpr const EnumValueSet VkShaderInfoTypeAMDSets[] = {
    {"STATISTICS_AMD", 0},
    {"BINARY_AMD", 1},
    {"DISASSEMBLY_AMD", 2},
};
constexpr const EnumValueSet VkQueueGlobalPriorityEXTSets[] = {
    {"LOW_EXT", 128},
    {"MEDIUM_EXT", 256},
    {"HIGH_EXT", 512},
    {"REALTIME_EXT", 1024},
};
constexpr const EnumValueSet VkDebugUtilsMessageSeverityFlagBitsEXTSets[] = {
    {"VERBOSE_BIT_EXT", 0x00000001},
    {"INFO_BIT_EXT", 0x00000010},
    {"WARNING_BIT_EXT", 0x00000100},
    {"ERROR_BIT_EXT", 0x00001000},
};
constexpr const EnumValueSet VkDebugUtilsMessageTypeFlagBitsEXTSets[] = {
    {"GENERAL_BIT_EXT", 0x00000001},
    {"VALIDATION_BIT_EXT", 0x00000002},
    {"PERFORMANCE_BIT_EXT", 0x00000004},
};
constexpr const EnumValueSet VkConservativeRasterizationModeEXTSets[] = {
    {"DISABLED_EXT", 0},
    {"OVERESTIMATE_EXT", 1},
    {"UNDERESTIMATE_EXT", 2},
};
constexpr const EnumValueSet VkDescriptorBindingFlagBitsSets[] = {
    {"UPDATE_AFTER_BIND_BIT", 0x00000001},
    {"UPDATE_UNUSED_WHILE_PENDING_BIT", 0x00000002},
    {"PARTIALLY_BOUND_BIT", 0x00000004},
    {"VARIABLE_DESCRIPTOR_COUNT_BIT", 0x00000008},
};
constexpr const EnumValueSet VkVendorIdSets[] = {
    {"VIV", 0x10001},
    {"VSI", 0x10002},
    {"KAZAN", 0x10003},
    {"CODEPLAY", 0x10004},
};
constexpr const EnumValueSet VkDriverIdSets[] = {
    {"AMD_PROPRIETARY", 1},         {"AMD_OPEN_SOURCE", 2},           {"MESA_RADV", 3},
    {"NVIDIA_PROPRIETARY", 4},      {"INTEL_PROPRIETARY_WINDOWS", 5}, {"INTEL_OPEN_SOURCE_MESA", 6},
    {"IMAGINATION_PROPRIETARY", 7}, {"QUALCOMM_PROPRIETARY", 8},      {"ARM_PROPRIETARY", 9},
    {"GOOGLE_SWIFTSHADER", 10},     {"GGP_PROPRIETARY", 11},          {"BROADCOM_PROPRIETARY", 12},
};
constexpr const EnumValueSet VkConditionalRenderingFlagBitsEXTSets[] = {
    {"INVERTED_BIT_EXT", 0x00000001},
};
constexpr const EnumValueSet VkResolveModeFlagBitsSets[] = {
    {"NONE", 0},
    {"SAMPLE_ZERO_BIT", 0x00000001},
    {"AVERAGE_BIT", 0x00000002},
    {"MIN_BIT", 0x00000004},
    {"MAX_BIT", 0x00000008},
};
constexpr const EnumValueSet VkShadingRatePaletteEntryNVSets[] = {
    {"NO_INVOCATIONS_NV", 0},
    {"16_INVOCATIONS_PER_PIXEL_NV", 1},
    {"8_INVOCATIONS_PER_PIXEL_NV", 2},
    {"4_INVOCATIONS_PER_PIXEL_NV", 3},
    {"2_INVOCATIONS_PER_PIXEL_NV", 4},
    {"1_INVOCATION_PER_PIXEL_NV", 5},
    {"1_INVOCATION_PER_2X1_PIXELS_NV", 6},
    {"1_INVOCATION_PER_1X2_PIXELS_NV", 7},
    {"1_INVOCATION_PER_2X2_PIXELS_NV", 8},
    {"1_INVOCATION_PER_4X2_PIXELS_NV", 9},
    {"1_INVOCATION_PER_2X4_PIXELS_NV", 10},
    {"1_INVOCATION_PER_4X4_PIXELS_NV", 11},
};
constexpr const EnumValueSet VkCoarseSampleOrderTypeNVSets[] = {
    {"DEFAULT_NV", 0},
    {"CUSTOM_NV", 1},
    {"PIXEL_MAJOR_NV", 2},
    {"SAMPLE_MAJOR_NV", 3},
};
constexpr const EnumValueSet VkGeometryInstanceFlagBitsNVSets[] = {
    {"TRIANGLE_CULL_DISABLE_BIT_NV", 0x00000001},
    {"TRIANGLE_FRONT_COUNTERCLOCKWISE_BIT_NV", 0x00000002},
    {"FORCE_OPAQUE_BIT_NV", 0x00000004},
    {"FORCE_NO_OPAQUE_BIT_NV", 0x00000008},
};
constexpr const EnumValueSet VkGeometryFlagBitsNVSets[] = {
    {"OPAQUE_BIT_NV", 0x00000001},
    {"NO_DUPLICATE_ANY_HIT_INVOCATION_BIT_NV", 0x00000002},
};
constexpr const EnumValueSet VkBuildAccelerationStructureFlagBitsNVSets[] = {
    {"ALLOW_UPDATE_BIT_NV", 0x00000001},      {"ALLOW_COMPACTION_BIT_NV", 0x00000002},
    {"PREFER_FAST_TRACE_BIT_NV", 0x00000004}, {"PREFER_FAST_BUILD_BIT_NV", 0x00000008},
    {"LOW_MEMORY_BIT_NV", 0x00000010},
};
constexpr const EnumValueSet VkCopyAccelerationStructureModeNVSets[] = {
    {"CLONE_NV", 0},
    {"COMPACT_NV", 1},
};
constexpr const EnumValueSet VkAccelerationStructureTypeNVSets[] = {
    {"TOP_LEVEL_NV", 0},
    {"BOTTOM_LEVEL_NV", 1},
};
constexpr const EnumValueSet VkGeometryTypeNVSets[] = {
    {"TRIANGLES_NV", 0},
    {"AABBS_NV", 1},
};
constexpr const EnumValueSet VkAccelerationStructureMemoryRequirementsTypeNVSets[] = {
    {"OBJECT_NV", 0},
    {"BUILD_SCRATCH_NV", 1},
    {"UPDATE_SCRATCH_NV", 2},
};
constexpr const EnumValueSet VkRayTracingShaderGroupTypeNVSets[] = {
    {"GENERAL_NV", 0},
    {"TRIANGLES_HIT_GROUP_NV", 1},
    {"PROCEDURAL_HIT_GROUP_NV", 2},
};
constexpr const EnumValueSet VkMemoryOverallocationBehaviorAMDSets[] = {
    {"DEFAULT_AMD", 0},
    {"ALLOWED_AMD", 1},
    {"DISALLOWED_AMD", 2},
};
constexpr const EnumValueSet VkFramebufferCreateFlagBitsSets[] = {};
constexpr const EnumValueSet VkScopeNVSets[] = {
    {"DEVICE_NV", 1},
    {"WORKGROUP_NV", 2},
    {"SUBGROUP_NV", 3},
    {"QUEUE_FAMILY_NV", 5},
};
constexpr const EnumValueSet VkComponentTypeNVSets[] = {
    {"FLOAT16_NV", 0}, {"FLOAT32_NV", 1}, {"FLOAT64_NV", 2}, {"SINT8_NV", 3},
    {"SINT16_NV", 4},  {"SINT32_NV", 5},  {"SINT64_NV", 6},  {"UINT8_NV", 7},
    {"UINT16_NV", 8},  {"UINT32_NV", 9},  {"UINT64_NV", 10},
};
constexpr const EnumValueSet VkPipelineCreationFeedbackFlagBitsEXTSets[] = {
    {"VALID_BIT_EXT", 0x00000001},
    {"APPLICATION_PIPELINE_CACHE_HIT_BIT_EXT", 0x00000002},
    {"BASE_PIPELINE_ACCELERATION_BIT_EXT", 0x00000004},
};
constexpr const EnumValueSet VkFullScreenExclusiveEXTSets[] = {
    {"DEFAULT_EXT", 0},
    {"ALLOWED_EXT", 1},
    {"DISALLOWED_EXT", 2},
    {"APPLICATION_CONTROLLED_EXT", 3},
};
constexpr const EnumValueSet VkPerformanceCounterScopeKHRSets[] = {
    {"COMMAND_BUFFER_KHR", 0},
    {"RENDER_PASS_KHR", 1},
    {"COMMAND_KHR", 2},
    {"VK_QUERY_SCOPE_COMMAND_BUFFER_KHR", 0},
    {"VK_QUERY_SCOPE_RENDER_PASS_KHR", 1},
    {"VK_QUERY_SCOPE_COMMAND_KHR", 2},
};
constexpr const EnumValueSet VkPerformanceCounterUnitKHRSets[] = {
    {"GENERIC_KHR", 0},
    {"PERCENTAGE_KHR", 1},
    {"NANOSECONDS_KHR", 2},
    {"BYTES_KHR", 3},
    {"BYTES_PER_SECOND_KHR", 4},
    {"KELVIN_KHR", 5},
    {"WATTS_KHR", 6},
    {"VOLTS_KHR", 7},
    {"AMPS_KHR", 8},
    {"HERTZ_KHR", 9},
    {"CYCLES_KHR", 10},
};
constexpr const EnumValueSet VkPerformanceCounterStorageKHRSets[] = {
    {"INT32_KHR", 0},  {"INT64_KHR", 1},   {"UINT32_KHR", 2},
    {"UINT64_KHR", 3}, {"FLOAT32_KHR", 4}, {"FLOAT64_KHR", 5},
};
constexpr const EnumValueSet VkPerformanceCounterDescriptionFlagBitsKHRSets[] = {
    {"PERFORMANCE_IMPACTING_KHR", 0x00000001},
    {"CONCURRENTLY_IMPACTED_KHR", 0x00000002},
};
constexpr const EnumValueSet VkAcquireProfilingLockFlagBitsKHRSets[] = {};
constexpr const EnumValueSet VkShaderCorePropertiesFlagBitsAMDSets[] = {};
constexpr const EnumValueSet VkPerformanceConfigurationTypeINTELSets[] = {
    {"COMMAND_QUEUE_METRICS_DISCOVERY_ACTIVATED_INTEL", 0},
};
constexpr const EnumValueSet VkQueryPoolSamplingModeINTELSets[] = {
    {"MANUAL_INTEL", 0},
};
constexpr const EnumValueSet VkPerformanceOverrideTypeINTELSets[] = {
    {"NULL_HARDWARE_INTEL", 0},
    {"FLUSH_GPU_CACHES_INTEL", 1},
};
constexpr const EnumValueSet VkPerformanceParameterTypeINTELSets[] = {
    {"HW_COUNTERS_SUPPORTED_INTEL", 0},
    {"STREAM_MARKER_VALID_BITS_INTEL", 1},
};
constexpr const EnumValueSet VkPerformanceValueTypeINTELSets[] = {
    {"UINT32_INTEL", 0}, {"UINT64_INTEL", 1}, {"FLOAT_INTEL", 2},
    {"BOOL_INTEL", 3},   {"STRING_INTEL", 4},
};
constexpr const EnumValueSet VkShaderFloatControlsIndependenceSets[] = {
    {"32_BIT_ONLY", 0},
    {"ALL", 1},
    {"NONE", 2},
};
constexpr const EnumValueSet VkPipelineExecutableStatisticFormatKHRSets[] = {
    {"BOOL32_KHR", 0},
    {"INT64_KHR", 1},
    {"UINT64_KHR", 2},
    {"FLOAT64_KHR", 3},
};
constexpr const EnumValueSet VkLineRasterizationModeEXTSets[] = {
    {"DEFAULT_EXT", 0},
    {"RECTANGULAR_EXT", 1},
    {"BRESENHAM_EXT", 2},
    {"RECTANGULAR_SMOOTH_EXT", 3},
};
constexpr const EnumValueSet VkShaderModuleCreateFlagBitsSets[] = {};
constexpr const EnumValueSet VkPipelineCompilerControlFlagBitsAMDSets[] = {};
constexpr const EnumValueSet VkToolPurposeFlagBitsEXTSets[] = {
    {"VALIDATION_BIT_EXT", 0x00000001},
    {"PROFILING_BIT_EXT", 0x00000002},
    {"TRACING_BIT_EXT", 0x00000004},
    {"ADDITIONAL_FEATURES_BIT_EXT", 0x00000008},
    {"MODIFYING_FEATURES_BIT_EXT", 0x00000010},
};

constexpr const EnumValueSet *valueSets[] = {
    VkImageLayoutSets,
    VkAttachmentLoadOpSets,
    VkAttachmentStoreOpSets,
    VkImageTypeSets,
    VkImageTilingSets,
    VkImageViewTypeSets,
    VkCommandBufferLevelSets,
    VkComponentSwizzleSets,
    VkDescriptorTypeSets,
    VkQueryTypeSets,
    VkBorderColorSets,
    VkPipelineBindPointSets,
    VkPipelineCacheHeaderVersionSets,
    VkPrimitiveTopologySets,
    VkSharingModeSets,
    VkIndexTypeSets,
    VkFilterSets,
    VkSamplerMipmapModeSets,
    VkSamplerAddressModeSets,
    VkCompareOpSets,
    VkPolygonModeSets,
    VkCullModeFlagBitsSets,
    VkFrontFaceSets,
    VkBlendFactorSets,
    VkBlendOpSets,
    VkStencilOpSets,
    VkLogicOpSets,
    VkInternalAllocationTypeSets,
    VkSystemAllocationScopeSets,
    VkPhysicalDeviceTypeSets,
    VkVertexInputRateSets,
    VkFormatSets,
    VkStructureTypeSets,
    VkSubpassContentsSets,
    VkDynamicStateSets,
    VkDescriptorUpdateTemplateTypeSets,
    VkObjectTypeSets,
    VkQueueFlagBitsSets,
    VkRenderPassCreateFlagBitsSets,
    VkDeviceQueueCreateFlagBitsSets,
    VkMemoryPropertyFlagBitsSets,
    VkMemoryHeapFlagBitsSets,
    VkAccessFlagBitsSets,
    VkBufferUsageFlagBitsSets,
    VkBufferCreateFlagBitsSets,
    VkShaderStageFlagBitsSets,
    VkImageUsageFlagBitsSets,
    VkImageCreateFlagBitsSets,
    VkImageViewCreateFlagBitsSets,
    VkSamplerCreateFlagBitsSets,
    VkPipelineCreateFlagBitsSets,
    VkPipelineShaderStageCreateFlagBitsSets,
    VkColorComponentFlagBitsSets,
    VkFenceCreateFlagBitsSets,
    VkSemaphoreCreateFlagBitsSets,
    VkFormatFeatureFlagBitsSets,
    VkQueryControlFlagBitsSets,
    VkQueryResultFlagBitsSets,
    VkCommandBufferUsageFlagBitsSets,
    VkQueryPipelineStatisticFlagBitsSets,
    VkImageAspectFlagBitsSets,
    VkSparseImageFormatFlagBitsSets,
    VkSparseMemoryBindFlagBitsSets,
    VkPipelineStageFlagBitsSets,
    VkCommandPoolCreateFlagBitsSets,
    VkCommandPoolResetFlagBitsSets,
    VkCommandBufferResetFlagBitsSets,
    VkSampleCountFlagBitsSets,
    VkAttachmentDescriptionFlagBitsSets,
    VkStencilFaceFlagBitsSets,
    VkDescriptorPoolCreateFlagBitsSets,
    VkDependencyFlagBitsSets,
    VkSemaphoreTypeSets,
    VkSemaphoreWaitFlagBitsSets,
    VkPresentModeKHRSets,
    VkColorSpaceKHRSets,
    VkDisplayPlaneAlphaFlagBitsKHRSets,
    VkCompositeAlphaFlagBitsKHRSets,
    VkSurfaceTransformFlagBitsKHRSets,
    VkSwapchainImageUsageFlagBitsANDROIDSets,
    VkTimeDomainEXTSets,
    VkDebugReportFlagBitsEXTSets,
    VkDebugReportObjectTypeEXTSets,
    VkRasterizationOrderAMDSets,
    VkExternalMemoryHandleTypeFlagBitsNVSets,
    VkExternalMemoryFeatureFlagBitsNVSets,
    VkValidationCheckEXTSets,
    VkValidationFeatureEnableEXTSets,
    VkValidationFeatureDisableEXTSets,
    VkSubgroupFeatureFlagBitsSets,
    VkIndirectCommandsLayoutUsageFlagBitsNVXSets,
    VkObjectEntryUsageFlagBitsNVXSets,
    VkIndirectCommandsTokenTypeNVXSets,
    VkObjectEntryTypeNVXSets,
    VkDescriptorSetLayoutCreateFlagBitsSets,
    VkExternalMemoryHandleTypeFlagBitsSets,
    VkExternalMemoryFeatureFlagBitsSets,
    VkExternalSemaphoreHandleTypeFlagBitsSets,
    VkExternalSemaphoreFeatureFlagBitsSets,
    VkSemaphoreImportFlagBitsSets,
    VkExternalFenceHandleTypeFlagBitsSets,
    VkExternalFenceFeatureFlagBitsSets,
    VkFenceImportFlagBitsSets,
    VkSurfaceCounterFlagBitsEXTSets,
    VkDisplayPowerStateEXTSets,
    VkDeviceEventTypeEXTSets,
    VkDisplayEventTypeEXTSets,
    VkPeerMemoryFeatureFlagBitsSets,
    VkMemoryAllocateFlagBitsSets,
    VkDeviceGroupPresentModeFlagBitsKHRSets,
    VkSwapchainCreateFlagBitsKHRSets,
    VkViewportCoordinateSwizzleNVSets,
    VkDiscardRectangleModeEXTSets,
    VkSubpassDescriptionFlagBitsSets,
    VkPointClippingBehaviorSets,
    VkSamplerReductionModeSets,
    VkTessellationDomainOriginSets,
    VkSamplerYcbcrModelConversionSets,
    VkSamplerYcbcrRangeSets,
    VkChromaLocationSets,
    VkBlendOverlapEXTSets,
    VkCoverageModulationModeNVSets,
    VkCoverageReductionModeNVSets,
    VkValidationCacheHeaderVersionEXTSets,
    VkShaderInfoTypeAMDSets,
    VkQueueGlobalPriorityEXTSets,
    VkDebugUtilsMessageSeverityFlagBitsEXTSets,
    VkDebugUtilsMessageTypeFlagBitsEXTSets,
    VkConservativeRasterizationModeEXTSets,
    VkDescriptorBindingFlagBitsSets,
    VkVendorIdSets,
    VkDriverIdSets,
    VkConditionalRenderingFlagBitsEXTSets,
    VkResolveModeFlagBitsSets,
    VkShadingRatePaletteEntryNVSets,
    VkCoarseSampleOrderTypeNVSets,
    VkGeometryInstanceFlagBitsNVSets,
    VkGeometryFlagBitsNVSets,
    VkBuildAccelerationStructureFlagBitsNVSets,
    VkCopyAccelerationStructureModeNVSets,
    VkAccelerationStructureTypeNVSets,
    VkGeometryTypeNVSets,
    VkAccelerationStructureMemoryRequirementsTypeNVSets,
    VkRayTracingShaderGroupTypeNVSets,
    VkMemoryOverallocationBehaviorAMDSets,
    VkFramebufferCreateFlagBitsSets,
    VkScopeNVSets,
    VkComponentTypeNVSets,
    VkPipelineCreationFeedbackFlagBitsEXTSets,
    VkFullScreenExclusiveEXTSets,
    VkPerformanceCounterScopeKHRSets,
    VkPerformanceCounterUnitKHRSets,
    VkPerformanceCounterStorageKHRSets,
    VkPerformanceCounterDescriptionFlagBitsKHRSets,
    VkAcquireProfilingLockFlagBitsKHRSets,
    VkShaderCorePropertiesFlagBitsAMDSets,
    VkPerformanceConfigurationTypeINTELSets,
    VkQueryPoolSamplingModeINTELSets,
    VkPerformanceOverrideTypeINTELSets,
    VkPerformanceParameterTypeINTELSets,
    VkPerformanceValueTypeINTELSets,
    VkShaderFloatControlsIndependenceSets,
    VkPipelineExecutableStatisticFormatKHRSets,
    VkLineRasterizationModeEXTSets,
    VkShaderModuleCreateFlagBitsSets,
    VkPipelineCompilerControlFlagBitsAMDSets,
    VkToolPurposeFlagBitsEXTSets,
};

/**
 * @brief Returns the start->end pointer range for valid value sets for the given typename
 * @param enumType Vulkan enum typename
 * @return Pointer range, or nullptr's if type isn't found.
 */
std::tuple<const EnumValueSet *, const EnumValueSet *> getValueSets(std::string_view enumType) {
    for (std::size_t i = 0; i < enumTypesCount; ++i) {
        if (enumType == std::string_view{enumTypes[i].name}) {
            return std::make_tuple(valueSets[i], valueSets[i] + enumTypes[i].count);
        }
    }

    return std::make_tuple(nullptr, nullptr);
}

/**
 * @brief Takes a given string and formats it for use with parsing
 * @param str The string to format
 * @return Formatted string
 *
 * First, any non alphanumeric characters are trimmed from both ends of the string.
 * After than, any spaces are replaced with underscores, and finally all the characters are
 * capitalized. This will generate the string closest to the original ones found in the XML spec.
 */
std::string formatString(std::string str) {
    // Trim left
    std::size_t cutOffset = 0;
    for (auto c : str) {
        if (isalnum(c, std::locale{}))
            break;
        else
            ++cutOffset;
    }
    str = str.substr(cutOffset);

    // Trim right
    cutOffset = 0;
    for (std::size_t i = 0; i < str.size(); ++i) {
        if (isalnum(str[i]))
            cutOffset = i + 1;
    }
    str = str.substr(0, cutOffset);

    std::replace(str.begin(), str.end(), ' ', '_');
    std::for_each(str.begin(), str.end(), [](char &c) { c = ::toupper(c); });

    return str;
}

/**
 * @brief Converts a Vulakn Flag typename into the prefix that is used for it's enums
 * @param typeName Name of the type to generate the Vk enum prefix for
 * @return Generated prefix string
 *
 * Any capitalized letters except for the first has an underscore inserted before it, an underscore
 * is added to the end, and all characters are converted to upper case.
 */
std::string processEnumPrefix(std::string_view typeName) {
    std::string retStr;

    for (std::size_t i = 0; i < vendorTagCount; ++i) {
        if (typeName.ends_with(vendorTags[i])) {
            typeName = typeName.substr(0, typeName.size() - strlen(vendorTags[i]));
            break;
        }
    }

    if (typeName.ends_with("FlagBits")) {
        typeName = typeName.substr(0, typeName.size() - strlen("FlagBits"));
    }

    for (auto it = typeName.begin(); it != typeName.end(); ++it) {
        if (it == typeName.begin()) {
            retStr += ::toupper(*it);
        } else if (::isupper(*it)) {
            retStr += '_';
            retStr += *it;
        } else {
            retStr += toupper(*it);
        }
    }
    retStr += '_';

    return retStr;
}

/**
 * @brief Returns the value for the given type/value
 * @param enumType Vulkan enum typename
 * @param enumPrefix The normal prefix for the enum's values
 * @param enumName Name of the enum value to find
 * @return The associated value, or zero if not found otherwise.
 */
uint32_t findValue(std::string_view enumType,
                   std::string_view enumPrefix,
                   std::string_view enumName) {
    // Figure out which ValueSet the enum given corresponds to
    auto [start, end] = getValueSets(enumType);

    // With the given sets/count, iterate until we find the value
    while (start != end) {
        if (enumName == std::string_view{start->name}) {
            return start->value;
        }

        std::string prefixedName{enumPrefix.begin(), enumPrefix.end()};
        prefixedName += start->name;
        if (enumName == prefixedName) {
            return start->value;
        }

        ++start;
    }

    return 0;
}

} // namespace

namespace vkEnum {

uint32_t parseEnum(std::string_view enumType, std::string value) {
    auto prefix = processEnumPrefix(enumType);
    value = formatString(value);

    return findValue(enumType, prefix, value);
}

uint32_t parseBitmask(std::string_view enumType, std::string value) {
    auto prefix = processEnumPrefix(enumType);
    uint32_t retVal = 0;

    auto startCh = value.begin();
    auto endCh = startCh;
    for (; endCh != value.end(); ++endCh) {
        if (*endCh == '|') {
            std::string token(startCh, endCh);
            token = formatString(token);

            retVal |= findValue(enumType, prefix, token);

            startCh = endCh + 1;
        }
    }
    if (startCh != endCh) {
        std::string token(startCh, endCh);
        token = formatString(token);

        retVal |= findValue(enumType, prefix, token);
    }

    return retVal;
}

std::string stringifyEnum(std::string_view enumType, uint32_t enumValue) {
    auto [start, end] = getValueSets(enumType);

    while (start != end) {
        if (start->value == enumValue) {
            return start->name;
        }

        ++start;
    }

    return "";
}

std::string stringifyBitmask(std::string_view enumType, uint32_t enumValue) {
    auto [end, start] = getValueSets(enumType);
    --end;
    --start;

    std::string retStr;

    while (start != end && enumValue != 0) {
        if ((start->value & enumValue) == start->value) {
            // Found a compatible bit mask, add it
            if (!retStr.empty()) {
                retStr += " | ";
            }
            retStr += start->name;
            enumValue = enumValue ^ start->value;
        }

        --start;
    }

    return retStr;
}

} // namespace vkEnum
